services:
    caddy:
        extends:
            file: docker-compose.yml
            service: caddy
        build:
            context: ../..
            dockerfile: docker/app/Dockerfile
            target: build-production
        image: dockerized-php-caddy:prod
