services:
    custom-caddy:
        extends:
            file: docker-compose.yml
            service: custom-caddy
        build:
            context: .
            dockerfile: Dockerfile
            target: build-production
        image: dockerized-php-caddy:prod
