services:
    apache-benchmark:
        container_name: apache-benchmark
        build:
            context: ..
            dockerfile: docker/apache-benchmark/Dockerfile
            target: build
        restart: unless-stopped
        tty: true
        extra_hosts:
            - localhost:${WEBSERVER_IPADDRESS}
        volumes:
            - ./apache-benchmark/endpoints:/endpoints
