services:
    caddy:
        extends:
            file: docker-compose.yml
            service: caddy
        container_name: caddy
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: build-development
        image: dockerized-php-caddy:dev
        environment:
            - PHP_XDEBUG_IDEKEY=PHPSTORM
            - PHP_XDEBUG_MODE=develop,coverage,debug,profile
            - PHP_XDEBUG_START_WITH_REQUEST=yes
            - PHP_XDEBUG_CLIENT_HOST=172.18.0.1
            - PHP_XDEBUG_CLIENT_PORT=9003
            - PHP_XDEBUG_MAX_NESTING_LEVEL=3000
            - PHP_XDEBUG_OUTPUT_DIR=/tmp/xdebug
            - PHP_XDEBUG_DISCOVER_CLIENT_HOST=false
            - PHP_XDEBUG_LOG=/dev/stdout
            - PHP_XDEBUG_LOG_LEVEL=0
        volumes:
            - ../src:/var/www/html
